# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 936aacec6551ae54fa651b1f10eb6382f61a4fd04376ce8e01718b9dca472b5c03745e71b641968d0190424be192bbc70e90aa98ff80a5c9b090cf61d3bef2b4

test:
  secret_key_base: 81bc4c6d256e8871c50787b9b3ba13a49e2e51a60a399b338671aa041bf5d10926c821eb6af0c9017f1e9c3c461be1903c103691f5f9a00a8ea3484daa7ed064

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
